name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      DATABASE_URL: "https://fake.com"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run TypeScript
      run: npm run build

    - name: Typechecking
      run: npm run typecheck

    - name: Lint
      run: npm run lint
